# Generated by Django 3.0.5 on 2022-04-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestPerformanceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=24)),
                ('time_consume', models.IntegerField()),
                ('threshold', models.IntegerField()),
                ('hit_num', models.IntegerField(default=0)),
                ('alerted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'index_together': {('path', 'method')},
            },
        ),
    ]
